tests
testInvalidPassports
	| passports |
	passports := passportParser getPassports: 'iyr:2013 ecl:amb cid:350 eyr:2023 pid:028048884
hcl:#cfa07d byr:1929' lines.
	self
		deny: (testSubject validatePassport: passports first).
	passports := passportParser getPassports: 'hcl:#cfa07d eyr:2025 pid:166559648
iyr:2011 ecl:brn hgt:59in' lines.
	self
		deny: (testSubject validatePassport: passports first)